### ISSUE TITLE
组件层叠顺序有问题呀

### ISSUE THREAD

**Issue by gl2summer** [pddon/pddon-win#4]
组件层叠顺序有问题呀，无论怎么调节组件顺序，“银行账户"都显示不到上面来。
![image](https://github.com/pddon/pddon-win/assets/23540949/6c9ca342-450e-4126-a960-6abd699ba429)

**Comment by pddon** [comment]
> 组件层叠顺序有问题呀，无论怎么调节组件顺序，“银行账户"都显示不到上面来。 ![image](https://private-user-images.githubusercontent.com/23540949/325643149-6c9ca342-450e-4126-a960-6abd699ba429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODg4MDksIm5iZiI6MTcxNDE4ODUwOSwicGF0aCI6Ii8yMzU0MDk0OS8zMjU2NDMxNDktNmM5Y2EzNDItNDUwZS00MTI2LWE5NjAtNmFiZDY5OWJhNDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAzMjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwM2QyODJhOTg5NDJjMzlkNzE5NTJjNDkyMzEwNjE4NmVlODk3M2FmNTc0Nzg1NTY3NjdhMzU5OWI3ZTVmYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IjT2o59Hw9UaSkeHixBa7LSCFs3gxeyjuDvUd6nn6Ow)

需要注意的一点是，被选中组件的层叠顺序会暂时被置顶，其他组件暂时无法上移最顶，取消选中后才可以哦！

**Comment by pddon** [comment]
经过仔细的测试，确实发现了一些场景出现了层叠顺序控制失效，版本v1.1.7已经修复了该问题，而且取消了功能：单个组件被选中后其层叠顺序临时置顶；
